language: objective-c
os: osx
sudo: enabled

osx_image: xcode11.1

xcode_workspace: Generika.xcworkspace

podfile: Podfile

install:
  - pod install --repo-update

matrix:
  include:
    - xcode_scheme: GenerikaTests
      xcode_sdk: iphonesimulator13.1
      env: OS_VERSION=13.1

script:
  - OS_VERSION=$OS_VERSION make test

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - yasuhiro.asaka@grauwoelfchen.net
      - zdavatz@ywesee.com
