language: objective-c
os: osx
sudo: enabled

branches:
  only:
    - master

xcode_workspace: Generika.xcworkspace
xcode_scheme: GenerikaTests
osx_image: xcode9.2

podfile: Podfile

before_install:
  - sudo gem install bundler --no-rdoc --no-ri --no-document
  - bundle install

install:
  - bundle exec pod install

script:
  - make test

notifications:
  email:
    on_success: change
    on_failure: always
    recipients:
      - yasuhiro.asaka@grauwoelfchen.net
      - zdavatz@ywesee.com
